// <auto-generated />
namespace projektMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class isBorrowed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isBorrowed));
        
        string IMigrationMetadata.Id
        {
            get { return "202106170747286_isBorrowed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
